---
all:
  - pen:     fineliner
    weight:  narrow
    width:   0.95
    color:   black
    opacity: 0.9

"0":
  - pen:     pen
    weight:  standard
    width:   3
    color:   red
    opacity: 0.5

  - pen:     fineliner
    weight:  narrow
    width:   0.8
    color:   blue
    opacity: 0.8

  - pen:     highlighter
    weight:  standard
    width:   5
    color:   orange
    opacity: 0.2
